site_name: Clean IoC
site_url: https://example.com/
nav:
  - Home: index.md
  - Simple Uses: simple-uses.md
  - Factories: factories.md
  - Lifespans: lifespans.md
  - Generics: generics.md
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences