site_name: Clean IoC
site_url: https://example.com/
repo_name: peter-daly/clean_ioc
repo_url: https://github.com/peter-daly/clean_ioc
nav:
  - Home: index.md
  - Simple Uses: simple-uses.md
  - Factories: factories.md
  - Lifespans: lifespans.md
  - Generics: generics.md
  - Decorators: decorators.md
  - Scopes: scopes.md
  - Pre-Configurations: pre-configurations.md
  - Bundles: bundles.md
  - Extensions:
    - FastAPI: extensions/fastapi.md
  - Background:
    - Inversion of Control: inversion-of-control.md
    - Dependency Injection: dependency-injection.md
    - SOLID: solid.md

theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences